//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skAmazon2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public CustomerOrder()
        {
            this.OrderLineItems = new HashSet<OrderLineItem>();
        }
    
        public int OrderId { get; set; }
        public int UserID { get; set; }
        public string DeliveryAddressID { get; set; }
        public int PaymentMethodID { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual skAmazonUser skAmazonUser { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
    }
}
