//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skAmazon2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public CustomerAddress()
        {
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public int AddressID { get; set; }
        public string AddrLine1 { get; set; }
        public string AddrLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Country { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserId { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}
