//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skAmazon2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public int PaymentMethodID { get; set; }
        public string PaymentDescription { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PaymentType { get; set; }
        public int BillingAddressID { get; set; }
        public string UserID { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}
