//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skAmazon2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.skAmazonUsers = new HashSet<skAmazonUser>();
        }
    
        public int PermissionID { get; set; }
        public string PermissionDescription { get; set; }
        public Nullable<bool> IsRegisteredCustomer { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
    
        public virtual ICollection<skAmazonUser> skAmazonUsers { get; set; }
    }
}
