//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skAmazon2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComment
    {
        public int CommentId { get; set; }
        public int ItemId { get; set; }
        public string UserId { get; set; }
        public string CommentText { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int Rating { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}
