//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skAmazon2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderLineItems = new HashSet<OrderLineItem>();
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int ItemID { get; set; }
        public string ProductDescription { get; set; }
        public decimal UnitPrice { get; set; }
        public int QoH { get; set; }
        public Nullable<int> Rating { get; set; }
        public int ManufacturerID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
    }
}
