//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skAmazon2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedItem
    {
        public int SavedItemId { get; set; }
        public int UserId { get; set; }
        public int ProductID { get; set; }
        public string ListName { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual skAmazonUser skAmazonUser { get; set; }
    }
}
