//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skAmazon2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skAmazonUser
    {
        public skAmazonUser()
        {
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.CustomerOrders = new HashSet<CustomerOrder>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.ProductComments = new HashSet<ProductComment>();
            this.SavedItems = new HashSet<SavedItem>();
        }
    
        public int UserID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int PermissionLevelID { get; set; }
    
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual ICollection<ProductComment> ProductComments { get; set; }
        public virtual ICollection<SavedItem> SavedItems { get; set; }
        public virtual skAmazonUserPassword skAmazonUserPassword { get; set; }
    }
}
